version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install kind
          command: |
            curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-linux-amd64
            chmod +x ./kind
      - run:
          name: Create Cluster
          command: ./kind create cluster
      - run:
          name: kubectl command
          command: |
            export KUBECONFIG="$(./kind get kubeconfig-path --name="kind")"
            kubectl get nodes
