version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout

      - run:
          name: Install kind
          command: GO111MODULE="on" go get sigs.k8s.io/kind@v0.5.1

      - run:
          name: Create Cluster
          command: sudo kind create cluster
